# Generated by Django 3.1.5 on 2021-02-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, help_text='Input email address of the account here (max length = 254).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, help_text='Input password of the account here (max length = 300).', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='summary',
            field=models.CharField(blank=True, help_text='Input summary of the account here (max length = 300).', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(blank=True, help_text='Input the user id of the account (max length = 80).', max_length=80, null=True),
        ),
    ]
